export default {
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_FAIL: 'ADD_USER_FAIL',
    USER_LOGGED_SUCCESS: 'USER_LOGGED_SUCCESS',
    USER_LOGGED_REQUEST: 'USER_LOGGED_REQUEST',
    USER_LOGGED_FAIL: 'USER_LOGGED_FAIL',
}
