export default {
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_FAIL: 'ADD_USER_FAIL',
    GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
    GET_LIST_REQUEST: 'GET_LIST_REQUEST',
    GET_LIST_FAIL: 'GET_LIST_FAIL',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_FAIL: 'UPDATE_PRODUCT_FAIL'
}
